sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - git clone --depth=50 --branch=master https://github.com/dustinbrown/python-anydo.git ~/dustinbrown/python-anydo
  - pip install tox-travis
#  - pip install tox-travis coveralls
script:
  - tox
#after_success:
#  coveralls --verbose
